export const data = {
  columns: [
    {
      id: 1,
      name: 'Сотрудник',
      sortField: 'name',
    },
    {
      id: 2,
      name: 'Сумма чаевых',
      sortField: 'summTips',
    },
    {
      id: 3,
      name: 'Рейтинг',
      sortField: 'rating',
    },
    {
      id: 4,
      name: 'Отзывов',
      sortField: 'feedbacks',
    },
    {
      id: 5,
      name: 'Положительных',
      sortField: 'good',
    },
    {
      id: 6,
      name: 'Отрицательных',
      sortField: 'bad',
    },
    {
      id: 7,
      name: 'Средняя сумма чаевых',
      sortField: 'averageTipAmount',
    },
  ],
  data: [
    {
      id: 1,
      name: 'Петр Иванович',
      summTips: '1010,00 руб.',
      rating: '5,0',
      feedbacks: 225,
      good: 35,
      bad: 251,
      averageTipAmount: '157,10 руб.',
    },
    {
      id: 2,
      name: 'Дмитрий Иванович',
      summTips: '11000,00 руб.',
      rating: '3,2',
      feedbacks: 502,
      good: 789,
      bad: 1,
      averageTipAmount: '157,00 руб.',
    },
    {
      id: 3,
      name: 'Владимир Иванович',
      summTips: '1000,54 руб.',
      rating: '3,0',
      feedbacks: 225,
      good: 110,
      bad: 53,
      averageTipAmount: '160,00 руб.',
    },
    {
      id: 4,
      name: 'Сергей Иванович',
      summTips: '1000,00 руб.',
      rating: '4,0',
      feedbacks: 752,
      good: 79,
      bad: 220,
      averageTipAmount: '159,00 руб.',
    },
    {
      id: 5,
      name: 'Владимир Иванович',
      summTips: '1000,54 руб.',
      rating: '3,0',
      feedbacks: 225,
      good: 110,
      bad: 53,
      averageTipAmount: '160,00 руб.',
    },
    {
      id: 6,
      name: 'Сергей Иванович',
      summTips: '1000,00 руб.',
      rating: '4,0',
      feedbacks: 752,
      good: 79,
      bad: 220,
      averageTipAmount: '159,00 руб.',
    },
  ]
}